### PR TITLE
Backport 1.13 underwater rendering to 1.12

### PR DESCRIPTION
**Pull request by embeddedt**
This PR backports several water-related features from Minecraft 1.13 and newer to Minecraft 1.12.

Summary of the implementation:

* The Forge fog events are used to adjust the fog color and density.
* Time spent underwater is tracked in the EntityPlayer mixin, similarly to how it is done in 1.13+.
* Water's light opacity has been adjusted from 3 to 1 to match the change made in 1.13.
* Bubble columns are now available as an optional feature.
* 1.13-style item floating is now available as an optional feature.
* The newer 1.13 water texture is now used.

I cannot claim to be anything close to a Forge expert, so please feel free to suggest changes/a different way of doing things.

The most glaring limitation is that 1.12 biomes do not specify a proper underwater fog color, and the surface color does not work so well with the 1.13 water texture, so I had to hardcode color values. This works for vanilla and Integrated Dynamics but will result in the default blue being used in other biomes.

### CODE REVIEW

**Comment by embeddedt** [comment]
Marking as a draft. This needs some more tweaks and testing. When I launched it in a larger modpack, the water light opacity change failed to apply.

**Comment by embeddedt** [comment]
Water opacity is now fixed.

**Comment by democat3457** [comment]
@Fuzss bump? these features would be nice in the official build

**Comment by embeddedt** [comment]
This has just been released as 1.4.0 on CurseForge. :tada:

**Pull request merged**
